"""CLI: run Phase 4 walk-forward verdict on the bot reverse signal."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

import pandas as pd

from signals.bot_walkforward import (
    BotBacktestConfig,
    BotWalkforwardConfig,
    run_walkforward,
)

DEFAULT_SIGNAL = Path("data/parquet/bot_reverse_signal.parquet")
DEFAULT_CANDLES_DIR = Path("data/parquet/candles")
DEFAULT_OUT = Path("data/parquet/phase4_bot_walkforward.parquet")
DEFAULT_TRADES_OUT = Path("data/parquet/phase4_bot_walkforward_trades.parquet")
DEFAULT_REPORT = Path("reports/phase4_bot_walkforward.md")
DEFAULT_TIMEFRAME = "1h"


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    signal_df = pd.read_parquet(args.signal)
    candles_by_coin = _load_candles(
        coins=tuple(signal_df["coin"].unique()),
        candles_dir=args.candles_dir,
        timeframe=args.timeframe,
    )
    result = run_walkforward(
        signal_df=signal_df,
        candles_by_coin=candles_by_coin,
        backtest_config=BotBacktestConfig(
            fees=args.fees,
            slippage=args.slippage,
            hold_hours=args.hold_hours,
        ),
        walkforward_config=BotWalkforwardConfig(
            n_splits=args.n_splits,
            mode=args.mode,
            min_train_days=args.min_train_days,
            test_days=args.test_days,
        ),
    )

    # Write per-fold parquet
    folds = pd.DataFrame(result["fold_stats"])
    folds["signal_path"] = str(args.signal)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    folds.to_parquet(args.out, index=False)
    print(f"wrote fold parquet: {args.out}")

    # Write trades parquet
    trades = result["oos_trades"]
    args.trades_out.parent.mkdir(parents=True, exist_ok=True)
    trades.to_parquet(args.trades_out, index=False)
    print(f"wrote trades parquet: {args.trades_out}")

    # Write report
    args.report.parent.mkdir(parents=True, exist_ok=True)
    _write_report(args.report, result, args)
    print(f"wrote report: {args.report}")

    # Print summary
    aggregate = result["aggregate"]
    print(
        f"\n=== verdict: {result['verdict']} ===\n"
        f"reason: {result['verdict_reason']}\n"
        f"n_trades: {aggregate['n_trades']}\n"
        f"sharpe: {aggregate['sharpe']:.3f}\n"
        f"win_rate: {aggregate['win_rate']:.3f}\n"
        f"max_dd: {aggregate['max_drawdown']:.3f}\n"
        f"total_return: {aggregate['total_return']:.3f}\n"
    )
    return 0


def _load_candles(
    *, coins: tuple[str, ...], candles_dir: Path, timeframe: str
) -> dict[str, pd.DataFrame]:
    candles_by_coin: dict[str, pd.DataFrame] = {}
    for coin in coins:
        path = candles_dir / f"{coin}_{timeframe}.parquet"
        if not path.exists():
            continue
        frame = pd.read_parquet(path)
        if "timestamp" in frame.columns:
            frame = frame.set_index(pd.DatetimeIndex(frame["timestamp"]))
        if frame.index.tz is None:
            frame = frame.set_index(frame.index.tz_localize("UTC"))
        candles_by_coin[coin] = frame
    return candles_by_coin


def _write_report(path: Path, result: dict, args: argparse.Namespace) -> None:
    aggregate = result["aggregate"]
    fold_stats = result["fold_stats"]
    lines: list[str] = []
    lines.append("# Phase 4 Bot Reverse Walk-Forward")
    lines.append("")
    lines.append(f"_Generated by {Path(__file__).name}_")
    lines.append("")
    lines.append("## Config")
    lines.append("")
    lines.append("| key | value |")
    lines.append("| --- | --- |")
    lines.append(f"| signal | {args.signal} |")
    lines.append(f"| n_splits | {args.n_splits} |")
    lines.append(f"| mode | {args.mode} |")
    lines.append(f"| min_train_days | {args.min_train_days} |")
    lines.append(f"| test_days | {args.test_days} |")
    lines.append(f"| fees | {args.fees} |")
    lines.append(f"| slippage | {args.slippage} |")
    lines.append(f"| hold_hours | {args.hold_hours} |")
    lines.append("")
    lines.append("## Aggregate")
    lines.append("")
    lines.append("| stat | value |")
    lines.append("| --- | ---: |")
    for key in (
        "n_trades",
        "sharpe",
        "mean_fold_sharpe",
        "win_rate",
        "max_drawdown",
        "total_return",
        "mean_return",
    ):
        if key in aggregate:
            value = aggregate[key]
            if isinstance(value, float):
                lines.append(f"| {key} | {value:.4f} |")
            else:
                lines.append(f"| {key} | {value} |")
    lines.append("")
    if fold_stats:
        lines.append("## Per-Fold OOS Stats")
        lines.append("")
        lines.append("| split | n_trades | Sharpe | win_rate | max_dd | total_return |")
        lines.append("| ---: | ---: | ---: | ---: | ---: | ---: |")
        for row in fold_stats:
            sharpe = row.get("sharpe", float("nan"))
            wr = row.get("win_rate", float("nan"))
            dd = row.get("max_drawdown", float("nan"))
            ret = row.get("total_return", float("nan"))
            lines.append(
                f"| {row['split_idx']} | {row['n_trades']} | "
                f"{sharpe:.3f} | {wr:.3f} | {dd:.3f} | {ret:.3f} |"
            )
        lines.append("")
    lines.append("## Verdict")
    lines.append("")
    lines.append(f"**{result['verdict']}** — {result['verdict_reason']}")
    lines.append("")
    path.write_text("\n".join(lines))


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Walk-forward verdict on Phase 4 bot reverse signal."
    )
    parser.add_argument("--signal", type=Path, default=DEFAULT_SIGNAL)
    parser.add_argument("--candles-dir", type=Path, default=DEFAULT_CANDLES_DIR)
    parser.add_argument("--timeframe", type=str, default=DEFAULT_TIMEFRAME)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--trades-out", type=Path, default=DEFAULT_TRADES_OUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--n-splits", type=int, default=3)
    parser.add_argument("--mode", choices=["expanding", "rolling"], default="expanding")
    parser.add_argument("--min-train-days", type=int, default=30)
    parser.add_argument("--test-days", type=int, default=15)
    parser.add_argument("--fees", type=float, default=0.0005)
    parser.add_argument("--slippage", type=float, default=0.0002)
    parser.add_argument("--hold-hours", type=int, default=24)
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
