"""CLI: walk-forward verdict on Phase 2.5 wallet reverse signal.

Converts ``reverse_alpha_scores`` per-fill scores to a signal frame, then runs
the same walk-forward harness used for Phase 4 bot signals
(``signals.bot_walkforward``). Per smart-search 2026-05-27 finding, n=21 wallet
pool is not a verdict bottleneck when walkforward operates at fill-level
(thousands of observations).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from signals.bot_walkforward import (
    BotBacktestConfig,
    BotWalkforwardConfig,
    run_walkforward,
)
from signals.wallet_reverse_signal import (
    WalletReverseSignalConfig,
    build_signal_frame,
)


DEFAULT_SCORES = Path("data/parquet/reverse_alpha_scores.parquet")
DEFAULT_FILLS_DIR = Path("data/parquet/fills")
DEFAULT_CANDLES_DIR = Path("data/parquet/candles")
DEFAULT_OUT = Path("data/parquet/phase2_5_slice5_walkforward.parquet")
DEFAULT_TRADES_OUT = Path("data/parquet/phase2_5_slice5_trades.parquet")
DEFAULT_REPORT = Path("reports/phase2_5_slice5_walkforward.md")
DEFAULT_TIMEFRAME = "1h"


def main() -> int:
    args = _parse_args()

    scores = pd.read_parquet(args.scores)
    signal_df = build_signal_frame(
        scores,
        args.fills_dir,
        config=WalletReverseSignalConfig(
            score_percentile=args.score_percentile,
            hold_hours=args.hold_hours,
        ),
    )

    if signal_df.empty:
        print(f"no signals built from {args.scores} at percentile={args.score_percentile}")
        return 1

    print(
        f"built signal frame: rows={len(signal_df)} "
        f"entries={int(signal_df['entry'].sum())} exits={int(signal_df['exit'].sum())} "
        f"coins={signal_df['coin'].nunique()} wallets={signal_df['wallet'].nunique()}"
    )

    candles_by_coin = _load_candles(
        coins=tuple(signal_df["coin"].unique()),
        candles_dir=args.candles_dir,
        timeframe=args.timeframe,
    )

    result = run_walkforward(
        signal_df=signal_df.drop(columns=["score", "wallet"]),
        candles_by_coin=candles_by_coin,
        backtest_config=BotBacktestConfig(
            fees=args.fees,
            slippage=args.slippage,
            hold_hours=args.hold_hours,
        ),
        walkforward_config=BotWalkforwardConfig(
            n_splits=args.n_splits,
            mode=args.mode,
            min_train_days=args.min_train_days,
            test_days=args.test_days,
        ),
    )

    folds = pd.DataFrame(result["fold_stats"])
    folds["scores_path"] = str(args.scores)
    folds["score_percentile"] = args.score_percentile
    args.out.parent.mkdir(parents=True, exist_ok=True)
    folds.to_parquet(args.out, index=False)
    print(f"wrote folds: {args.out}")

    trades = result["all_trades"]
    args.trades_out.parent.mkdir(parents=True, exist_ok=True)
    trades.to_parquet(args.trades_out, index=False)
    print(f"wrote trades: {args.trades_out}")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    _write_report(args.report, result, args, signal_df)
    print(f"wrote report: {args.report}")

    aggregate = result["aggregate"]
    print(
        f"\n=== verdict: {result['verdict']} ===\n"
        f"reason: {result['verdict_reason']}\n"
        f"n_trades: {aggregate['n_trades']}\n"
        f"sharpe: {aggregate['sharpe']:.3f}\n"
        f"win_rate: {aggregate['win_rate']:.3f}\n"
        f"max_dd: {aggregate['max_drawdown']:.3f}\n"
        f"total_return: {aggregate['total_return']:.3f}\n"
    )
    return 0


def _load_candles(
    *, coins: tuple[str, ...], candles_dir: Path, timeframe: str
) -> dict[str, pd.DataFrame]:
    candles: dict[str, pd.DataFrame] = {}
    for coin in coins:
        path = candles_dir / f"{coin}_{timeframe}.parquet"
        if not path.exists():
            continue
        frame = pd.read_parquet(path)
        if "timestamp" in frame.columns:
            frame = frame.set_index(pd.DatetimeIndex(frame["timestamp"]))
        if frame.index.tz is None:
            frame = frame.set_index(frame.index.tz_localize("UTC"))
        candles[coin] = frame
    return candles


def _write_report(path: Path, result: dict, args: argparse.Namespace, signal_df: pd.DataFrame) -> None:
    aggregate = result["aggregate"]
    fold_stats = result["fold_stats"]
    lines: list[str] = [
        "# Phase 2.5 Slice 5 — Wallet Reverse Signal Walk-Forward",
        "",
        f"_Generated by {Path(__file__).name}_",
        "",
        "## Config",
        "",
        "| key | value |",
        "| --- | --- |",
        f"| scores | {args.scores} |",
        f"| score_percentile | {args.score_percentile} |",
        f"| n_splits | {args.n_splits} |",
        f"| mode | {args.mode} |",
        f"| min_train_days | {args.min_train_days} |",
        f"| test_days | {args.test_days} |",
        f"| fees | {args.fees} |",
        f"| slippage | {args.slippage} |",
        f"| hold_hours | {args.hold_hours} |",
        "",
        "## Signal Frame Summary",
        "",
        "| stat | value |",
        "| --- | ---: |",
        f"| signal rows | {len(signal_df)} |",
        f"| entries | {int(signal_df['entry'].sum())} |",
        f"| exits | {int(signal_df['exit'].sum())} |",
        f"| unique coins | {signal_df['coin'].nunique()} |",
        f"| unique wallets | {signal_df['wallet'].nunique()} |",
        "",
        "## Aggregate",
        "",
        "| stat | value |",
        "| --- | ---: |",
    ]
    for key in ("n_trades", "sharpe", "mean_fold_sharpe", "win_rate", "max_drawdown", "total_return", "mean_return"):
        if key in aggregate:
            value = aggregate[key]
            if isinstance(value, float):
                lines.append(f"| {key} | {value:.4f} |")
            else:
                lines.append(f"| {key} | {value} |")
    lines.append("")
    if fold_stats:
        lines += [
            "## Per-Fold OOS",
            "",
            "| split | n_trades | Sharpe | win_rate | max_dd | total_return |",
            "| ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
        for row in fold_stats:
            lines.append(
                f"| {row['split_idx']} | {row['n_trades']} | "
                f"{row.get('sharpe', float('nan')):.3f} | "
                f"{row.get('win_rate', float('nan')):.3f} | "
                f"{row.get('max_drawdown', float('nan')):.3f} | "
                f"{row.get('total_return', float('nan')):.3f} |"
            )
        lines.append("")
    lines += [
        "## Verdict",
        "",
        f"**{result['verdict']}** — {result['verdict_reason']}",
        "",
    ]
    path.write_text("\n".join(lines))


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase 2.5 Slice 5 walk-forward verdict.")
    parser.add_argument("--scores", type=Path, default=DEFAULT_SCORES)
    parser.add_argument("--fills-dir", type=Path, default=DEFAULT_FILLS_DIR)
    parser.add_argument("--candles-dir", type=Path, default=DEFAULT_CANDLES_DIR)
    parser.add_argument("--timeframe", type=str, default=DEFAULT_TIMEFRAME)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--trades-out", type=Path, default=DEFAULT_TRADES_OUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--score-percentile", type=float, default=0.75)
    parser.add_argument("--n-splits", type=int, default=3)
    parser.add_argument("--mode", choices=["expanding", "rolling"], default="expanding")
    parser.add_argument("--min-train-days", type=int, default=30)
    parser.add_argument("--test-days", type=int, default=15)
    parser.add_argument("--fees", type=float, default=0.0005)
    parser.add_argument("--slippage", type=float, default=0.0002)
    parser.add_argument("--hold-hours", type=int, default=24)
    return parser.parse_args()


if __name__ == "__main__":
    raise SystemExit(main())
